import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

# This file was generated by ChatGPT 5.3

def plot_switching_vs_confidence_gap(
    model,
    df: pd.DataFrame,
    confidence_col: str = "confidence_gap",
    condition_col: str = "condition",
    title: str | None = None,
):

    x_vals = np.linspace(-1, 1, 200)

    condition_value = df[condition_col].iloc[0]

    pred_df = pd.DataFrame({
        confidence_col: x_vals,
        condition_col: condition_value
    })

    pred_res = model.get_prediction(pred_df).summary_frame(alpha=0.05)

    def find_col(cols, keywords):
        for c in cols:
            if any(k in c for k in keywords):
                return c
        raise ValueError(f"Could not find column with keywords {keywords} in {cols}")

    cols = pred_res.columns

    mean_col = find_col(cols, ["mean", "predicted"])
    lower_col = find_col(cols, ["lower"])
    upper_col = find_col(cols, ["upper"])

    pred_df["mean"] = pred_res[mean_col]
    pred_df["ci_lower"] = pred_res[lower_col]
    pred_df["ci_upper"] = pred_res[upper_col]
    pred_df[["mean", "ci_lower", "ci_upper"]] = pred_df[
        ["mean", "ci_lower", "ci_upper"]
    ].clip(0, 1)

    plt.rcParams.update({
        "font.family": "sans-serif",
        "font.size": 11,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "axes.spines.left": False,
        "axes.spines.bottom": False,
    })

    fig, ax = plt.subplots(figsize=(7, 4.5))

    line_color = "#593032"
    ci_color = "#6F8489"

    ax.plot(
        pred_df[confidence_col],
        pred_df["mean"],
        color=line_color,
        linewidth=2.5
    )

    for i in range(len(pred_df)):
        ax.vlines(
            pred_df[confidence_col].iloc[i],
            pred_df["ci_lower"].iloc[i],
            pred_df["ci_upper"].iloc[i],
            colors=ci_color,
            linewidth=2,
            alpha=0.25,
            capstyle="round"
        )

    ax.tick_params(axis='x', pad=5)
    ax.tick_params(axis='y', pad=5)

    ax.set_xlim(-1, 1)
    ax.set_ylim(0, 1)

    ax.set_xlabel("Confidence Gap")
    ax.set_ylabel("Predicted Probability of Switching")

    if title:
        ax.set_title(title, pad=12)

    ax.tick_params(axis='y', length=0)
    ax.tick_params(axis='x', length=0)

    ax.grid(axis="y", linestyle="-", alpha=0.2)
    ax.set_axisbelow(True)

    ax.fill_between(
        pred_df[confidence_col],
        pred_df["ci_lower"],
        pred_df["ci_upper"],
        color=ci_color,
        alpha=0.25
    )

    plt.tight_layout()
    plt.show()